# This is a basic workflow to help you get started with Actions

name: Running api tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 Checkout the code from master branch
        uses: actions/checkout@v3
      
      - name: Step 2 run maven tests
        run: |
             mvn clean test
             mvn -Dmaven.test.skip=true surefire-report:report
        
      - name: Step 3 Check the files in target folder
        if: always()
        run: |
              cd target
              ls -a
                    
      - name: Step 4 Use upload artifacts github actions
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: reports-generated
           path: /home/runner/work/payouts_api/payouts_api/target

      
